# Generated by Django 5.1.2 on 2024-11-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signindb',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signindb',
            name='username',
        ),
        migrations.AddField(
            model_name='signindb',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
