# Generated by Django 5.1.2 on 2024-11-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_remove_signindb_email_remove_signindb_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signindb',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signindb',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
