# Generated by Django 5.1.2 on 2024-11-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_employeedb_servicedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedb',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
