# Generated by Django 5.1.2 on 2024-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_employeedb_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedb',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
