# Generated by Django 5.1.2 on 2024-11-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='employee',
        ),
        migrations.DeleteModel(
            name='CoinPurchase',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
