# Generated by Django 5.1.2 on 2024-10-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_jobapplicationdb_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicationdb',
            name='date',
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
