# Generated by Django 5.1.2 on 2024-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_jobapplicationdb_date_bookingdb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='job_code',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
