# Generated by Django 5.1.2 on 2024-11-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlumberPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('employee_code', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
