# Generated by Django 5.1.2 on 2024-11-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_plumberpartner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobapplicationdb',
        ),
    ]
